### ISSUE TITLE
Should FROM_TIMESTAMP be optional?

### ISSUE THREAD

**Issue by redisec** [logzio/salesforce-logs-receiver#7]
Would it make sense to make FROM_TIMESTAMP parameter optional and default it to the CURRENT_TIME minus 60 min?
The reason for it would be: if docker container stops for any reason and then is restarted manually or automatically (in AWS ECS), we do not want it to re-fetch all logs from the beginning of time as defined by FROM_TIMESTAMP environment variable.

**Comment by Doron-Bargo** [comment]
Hi @redisec its a good improvement . We will work on it

**Comment by ShiranAvidov** [comment]
Thanks for the great suggestion.

**Comment by redisec** [comment]
Thank you for addressing this! I will test it today.
